language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
scala:
  - 2.12.11
  - 2.13.2
jdk:
  - openjdk11
env:
  - SCALAJS_VERSION=0.6.33
  - SCALAJS_VERSION=

matrix:
  include:
    - scala: 2.13.1
      jdk: openjdk11
      env: SCALAJS_VERSION= JOB_NAME="format and doc"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll scalafmtSbtCheck

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.cache/coursier"
    - "$HOME/.sbt"
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -print -delete
  - find $HOME/.cache/coursier -name "*.lock"               -print -delete
  - find $HOME/.sbt            -name "*.lock"               -print -delete
