name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [2.13.5, 2.12.13]
        nodejs: [14.15.4]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - uses: coursier/cache-action@v6
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.nodejs }}
      - run: npm install
      - name: Run Tests
        run: sbt ++${{ matrix.scala }} test scalafmtCheckAll scalafmtSbtCheck
        env:
          NODEJS_VERSION: ${{ matrix.nodejs }}
