name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [2.13.7, 2.12.15]
        nodejs: [14.18.1]
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - uses: coursier/cache-action@v6
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.nodejs }}
      - run: npm install
      - name: Run Tests
        run: sbt ++${{ matrix.scala }} test scalafmtCheckAll scalafmtSbtCheck
        env:
          NODEJS_VERSION: ${{ matrix.nodejs }}
